In [1]:
##Number 1

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 1, 1, 1], [2, -1, 3, 4], [-3, 2, -2, 5], [1, -1, 4, -1]])
B = np.array([10, 8, -3, 5])

In [4]:
ans = np.linalg.solve(A, B)

In [5]:
ans

array([3.44339623, 4.69811321, 1.62264151, 0.23584906])

In [6]:
##Number 2

##import numpy as np

In [7]:
A = np.array([[2, 1, 3], [1, 2, 1], [3, 1, 2]])  

In [8]:
A_inv = np.linalg.inv(A)

In [9]:
print(A_inv)

[[-0.375 -0.125  0.625]
 [-0.125  0.625 -0.125]
 [ 0.625 -0.125 -0.375]]


In [10]:
##Number 2

In [11]:
I = np.array([[1500,-600,0],[0,600,900],[1,1,-1]])
V = np.array([12,15,0])

CV = np.linalg.solve (I,V)

I1, I2, I3 = CV

print (I1, I2, I3)
print ((I1*1500)-(I2*600))
print ((I2*600)+(I3*900))

0.00967741935483871 0.004193548387096773 0.013870967741935485
12.000000000000002
15.0
